version: "3.0"
services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      APP_PORT: 5000
    volumes:
      - ./:/app/
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge